### ISSUE TITLE
logged in validation.

### ISSUE THREAD

**Issue by sultanassi95** [facg3/MWM-Chat#20]
Good Job guys, I'll be posting some {user experience} related issues.
LOGGED IN VALIDATION ..
if am logged in, and went back to login page, it won't re-direct me to chat form.
and it's the same for the register page..
![deepinscreenshot_20171231081903](https://user-images.githubusercontent.com/30059014/34459804-480df4c6-ee03-11e7-9eb6-0a18e07912e8.png)

**Comment by MahmoudMH** [comment]
thanks done :+1:
