### ISSUE TITLE
Password Validation - upon register {user-experience}

### ISSUE THREAD

**Issue by sultanassi95** [facg3/MWM-Chat#21]
Heey,
I think it's a very necessary step to be adding a password validation field when a user goes to register into your website.
![deepinscreenshot_20171231082057](https://user-images.githubusercontent.com/30059014/34459807-8a7bfa56-ee03-11e7-937e-1d07626f20f8.png)

**Comment by MahmoudMH** [comment]
thanks done
:+1:
