### ISSUE TITLE
Chat box scroll position {user experience}

### ISSUE THREAD

**Issue by sultanassi95** [facg3/MWM-Chat#23]
Heey <3
hmm, when I go to the Chat box page, I think the scroll box should be at the buttom of the box not at the beggining of it, imagine there is a thousend messege and I have to scroll down to the end to view the last one!
![deepinscreenshot_20171231082329](https://user-images.githubusercontent.com/30059014/34459819-e935a254-ee03-11e7-9e9b-5c55fb3708b0.png)

**Comment by MahmoudMH** [comment]
we did it :100:

**Comment by sultanassi95** [comment]
good job
