### ISSUE TITLE
use 'submit' even listener

### ISSUE THREAD

**Issue by Walidmash** [facg3/MWM-Chat#28]
Instead of making two even listeners 
https://github.com/facg3/MWM-Chat/blob/86b2915bd7d778383b4d227a56668b791430906a/public/js/registerDom.js#L30
https://github.com/facg3/MWM-Chat/blob/86b2915bd7d778383b4d227a56668b791430906a/public/js/registerDom.js#L33
you can just make a 'submit' listener on the form, which will handle both the click event and keypress enter even

**Comment by marwa7med** [comment]
Done !!
